include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Altilium
Altilium_FILES = Altilium.xm
Altilium_FRAMEWORKS = UIKit
Altilium_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/tweak.mk
include $(THEOS)/makefiles/aggregate.mk